# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b40949f37ae5f1027e08ff7c6aec0d79bc603465459c87f8c84524367532b7006eacb4ef11b07c8465618624f2b5405cf47cbe6f474fe11a3656a20a82fbb509
  twitter_api_key: noNYfsjoIogwPqzGLx7ZVvNlz
  twitter_api_secret: OlAjShFCwsVpTyPgjb0oWVbsqPgsL9WgTKQTz0NsEfZ6rLjrFW

test:
  secret_key_base: 5002378343e77be2989a613bf61ca6db55e3f8cdd3b89da37c9b88c9960b138cdf6febe4e130426de79ff8f0eaf1c2ab66b8b89a821067f4b64b59ae519e8da7

# Do not keep production secrets in the repository,
# instead read values from the environment - need to check how to do this!
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  # twitter_api_key: <%= ENV["TWITTER_API_KEY"] %>
  # twitter_api_secret: <%= ENV["TWITTER_API_SECRET"] %>
